baseURL = "https://bambu.bangunan.co/"
languageCode = "id"
title = "Jual Bambu Tali | Jual Bambu Tali, Bambu Steger, Bambu Hitam, Bambu Hias"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Tempat Jual Bambu Tali Terdekat - Kami menyediakan bambu tali, bambu steger, bambu hitam, dan bambu hias dengan harga terbaik dan gratis ongkir"
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jual bambu tali", "bambu steger", "bambu hitam", "bambu hias", "bambu murah", "bambu terdekat", "bambu kualitas terbaik", "bambu dekorasi"]
  base_price = 5000
  price_range = 2000
  free_shipping = true
  materials = [
  "Bambu Tali",
  "Bambu Steger",
  "Bambu Hitam",
  "Bambu Hias",
  "Bambu Petung",
  "Bambu Kuning"
  ]
  categories = ["Bambu Tali", "Bambu Steger", "Bambu Hitam", "Bambu Hias", "Bambu Petung", "Bambu Kuning"]
  payment_methods = ["COD (Cash On Delivery)", "Transfer Bank", "Bayar Ditempat", "Transfer Setelah Pengiriman"]
  area_served = [
    "Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Bandung", "Cimahi", "Sukabumi", "Cirebon", "Garut", "Tasikmalaya", "Sumedang", "Subang", "Karawang", "Purwakarta", "Cianjur", "Majalengka", "Indramayu", "Kuningan", "Banjar", "Pangandaran", "Kabupaten Bandung", "Kabupaten Bogor", "Kabupaten Bekasi", "Kabupaten Cirebon", "Kabupaten Garut", "Kabupaten Indramayu", "Kabupaten Karawang", "Kabupaten Kuningan", "Kabupaten Majalengka", "Kabupaten Pangandaran", "Kabupaten Purwakarta", "Kabupaten Subang", "Kabupaten Sukabumi", "Kabupaten Sumedang", "Kabupaten Tasikmalaya", "Serang", "Cilegon", "Tangerang Selatan", "Lebak", "Pandeglang", "Kabupaten Tangerang", "Kabupaten Serang", "Semarang", "Surakarta", "Magelang", "Salatiga", "Pekalongan", "Tegal", "Cilacap", "Purwokerto", "Pati", "Jepara", "Kudus", "Demak", "Blora", "Grobogan", "Kendal", "Temanggung", "Wonosobo", "Purworejo", "Kabupaten Magelang", "Kabupaten Boyolali", "Kabupaten Klaten", "Kabupaten Sragen", "Kabupaten Karanganyar", "Kabupaten Sukoharjo", "Kabupaten Wonogiri", "Kabupaten Pati", "Kabupaten Blora", "Kabupaten Grobogan", "Kabupaten Kudus", "Kabupaten Jepara", "Kabupaten Demak", "Kabupaten Batang", "Kabupaten Pekalongan", "Kabupaten Pemalang", "Kabupaten Tegal", "Kabupaten Brebes", "Kabupaten Cilacap", "Kabupaten Banyumas", "Kabupaten Purbalingga", "Kabupaten Banjarnegara", "Kabupaten Kebumen", "Kabupaten Temanggung", "Kabupaten Wonosobo", "Kabupaten Kendal", "Kabupaten Semarang", "Kabupaten Purworejo", "Surabaya", "Malang", "Batu", "Blitar", "Kediri", "Mojokerto", "Madiun", "Pasuruan", "Probolinggo", "Jember", "Lumajang", "Bondowoso", "Banyuwangi", "Situbondo", "Ngawi", "Magetan", "Pacitan", "Ponorogo", "Trenggalek", "Tulungagung", "Kabupaten Sidoarjo", "Kabupaten Gresik", "Kabupaten Lamongan", "Kabupaten Bojonegoro", "Kabupaten Tuban", "Kabupaten Jombang", "Kabupaten Nganjuk", "Kabupaten Madiun", "Kabupaten Magetan", "Kabupaten Ngawi", "Kabupaten Pacitan", "Kabupaten Ponorogo", "Kabupaten Blitar", "Kabupaten Tulungagung", "Kabupaten Kediri", "Kabupaten Malang", "Kabupaten Probolinggo", "Kabupaten Pasuruan", "Kabupaten Lumajang", "Kabupaten Jember", "Kabupaten Bondowoso", "Kabupaten Banyuwangi", "Kabupaten Situbondo"
  ]
  return_policies = [
  "Barang bisa ditukar dalam 1 hari jika tidak sesuai.",
  "Penggantian atau pengembalian gratis untuk bambu yang rusak atau cacat.",
  "Barang yang tidak sesuai pesanan dapat dikembalikan tanpa biaya tambahan."
  ]

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Jual Berbagai Jenis Bambu"
  hero_description = "Temukan koleksi bambu berkualitas kami, termasuk Bambu Tali, Bambu Steger, Bambu Hitam, dan Bambu Hias. Solusi terbaik untuk kebutuhan bambu Anda."
  hero_cta_text = "Lebih Detail"
  services_cta_text = "Lihat Daftar Harga"

  # Footer Section
  footer_about_title = "Keunggulan Kami"
  footer_about_description = "Jangkauan Kami Luas, Bebas biaya pengirirman, Bebas biaya bongkar muat, Cara Pemesanan yang mudah, Sistem pembayaran COD 100% aman, Buka setiap hari, Gratis konsultasi dan Stok bambu yang melimpah"
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "Bambu.bangunan.co menyediakan berbagai jenis bambu berkualitas tinggi, termasuk Bambu Tali, Bambu Steger, Bambu Hitam, dan Bambu Hias. Kami menawarkan produk dengan harga terjangkau dan layanan profesional, memastikan setiap pesanan memenuhi standar terbaik. Pilih kami untuk solusi bambu terbaik yang sesuai dengan kebutuhan Anda."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Agus|Rudi|Andi|Eko|Fajar|Toni|Samsul|Dedi|Wawan}"
  message = "{Saya membeli|Saya memesan|Saya menggunakan} bambu tali dari bambu.bangunan.co dan {kualitasnya sangat memuaskan|hasilnya luar biasa|kualitasnya benar-benar unggul}. {Cocok|Sangat pas|Ideal} untuk kebutuhan {proyek|pembangunan|konstruksi} saya dan {harganya sangat bersaing|harga yang ditawarkan cukup kompetitif|harga yang diberikan sangat menarik}."
  response = "{Terima kasih atas ulasannya! Kami senang bambu tali kami {memenuhi kebutuhan|sesuai dengan kebutuhan|mendukung proyek} proyek Anda.|Terima kasih, atas kepercayaannya. Kami senang produk bambu tali kami dapat {membantu|menyempurnakan|memfasilitasi} proyek Anda.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Rina|Ayu|Lina|Dewi|Fitri|Diah|Maya|Nur|Sari}"
  message = "Bambu steger yang saya beli {di sini|di bambu.bangunan.co|dari toko ini} {sangat kuat|benar-benar kokoh|luar biasa kokoh} dan {tahan lama|awet|sangat durable}. {Layanan pengiriman|Pengirimannya|Proses pengantaran} juga {cepat|efisien|tepat waktu} dan {efisien|tanpa kendala|sesuai harapan}. {Sangat puas|Saya benar-benar puas|Saya sangat senang} dengan pembelian ini."
  response = "{Kami sangat menghargai kepercayaan Anda. Senang mendengar bahwa bambu steger kami {sesuai dengan harapan|memenuhi ekspektasi|tepat dengan kebutuhan} Anda.|Terima kasih! Kami senang dapat menyediakan bambu steger berkualitas yang mendukung proyek Anda.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Bayu|Toni|Galih|Bambang|Ali|Rizal|Faisal|Yanto|Deni}"
  message = "Bambu hitam dari bambu.bangunan.co {memiliki kualitas yang sangat baik|berkualitas tinggi|luar biasa} dan {warna yang konsisten|warnanya seragam|warna hitamnya sangat bagus}. {Ideal|Cocok|Pas} untuk {desain lanskap|taman|proyek lanskap} saya."
  response = "{Terima kasih! Kami berkomitmen untuk menyediakan bambu hitam {berkualitas tinggi|terbaik|unggulan} untuk memenuhi kebutuhan desain Anda.|Terima kasih! Kami senang bambu hitam kami {dapat mendukung|memenuhi kebutuhan|tepat untuk} proyek desain lanskap Anda.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Agus|Rudi|Hendra|Toni|Wawan|Gilang|Ari|Benny|Yudi}"
  message = "{Saya sangat puas|Saya senang sekali|Saya benar-benar puas} dengan bambu hias yang saya beli. {Produk|Bambu} ini {membuat taman saya lebih indah|menambah keindahan taman saya|membuat tampilan taman semakin eksotis} dan {eksotis|unik|berkelas}. {Sangat rekomended|Sangat saya rekomendasikan|Benar-benar layak direkomendasikan}!"
  response = "{Senang mendengar bahwa bambu hias kami {membuat taman Anda lebih indah|menambah keindahan taman Anda|memperindah taman Anda}. Terima kasih atas dukungannya!|Terima kasih! Kami senang produk kami dapat {menambah keindahan|mempercantik|menyempurnakan} taman Anda.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Siti|Lina|Ayu|Dewi|Fitri|Diah|Nur|Maya|Sari}"
  message = "{Pelayanan di bambu.bangunan.co|Layanan yang saya terima dari bambu.bangunan.co} {sangat baik|luar biasa|memuaskan} dan {informatif|memberikan banyak informasi|sangat membantu}. Bambu tali yang saya beli {sangat sesuai|pas sekali|ideal} untuk {proyek kerajinan|pembuatan kerajinan|pekerjaan kerajinan} saya."
  response = "{Terima kasih! Kami senang bambu tali kami {cocok untuk|sesuai dengan|tepat untuk} proyek kerajinan Anda.|Terima kasih, atas kepercayaannya. Kami senang produk kami dapat mendukung proyek kerajinan Anda.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Rio|Galih|Faisal|Benny|Wawan|Toni|Rizal|Joko|Yanto}"
  message = "{Bambu hias yang saya beli|Produk bambu hias dari bambu.bangunan.co} {sangat berkualitas|berkualitas tinggi|memiliki kualitas yang sangat baik} dan {memberikan tampilan yang menarik|membuat ruang interior saya lebih indah|menciptakan suasana yang eksotis} pada {ruang interior|ruangan dalam|desain interior} saya. {Pembelian yang sangat memuaskan|Benar-benar puas dengan pembelian ini|Saya sangat puas dengan produk ini}."
  response = "{Kami senang mendengar bahwa bambu hias kami {mempercantik|memperindah|menambah keindahan} ruang interior Anda. Terima kasih atas ulasannya!|Terima kasih! Kami senang produk kami dapat {memenuhi harapan|sesuai ekspektasi|tepat untuk} kebutuhan desain interior Anda.}"
  rating = 5

[[params.tabelItems]]
  name = "Bambu Tali"
  price = "18.000 /batang"
[[params.tabelItems]]
  name = "Bambu Steger"
  price = "18.000 /batang"
[[params.tabelItems]]
  name = "Bambu Hitam"
  price = "25.000 /batang"
[[params.tabelItems]]
  name = "Bambu Hias"
  price = "20.000 /batang"
[[params.tabelItems]]
  name = "Bambu Petung"
  price = "25.000 /batang"
[[params.tabelItems]]
  name = "Bambu Kuning"
  price = "18.000 /batang"

[params.appliList]
  "Bambu Tali" = "digunakan untuk konstruksi bangunan, rangkaian atap, dan proyek pertanian"
  "Bambu Steger" = "digunakan untuk steger bangunan sementara pada proyek konstruksi"
  "Bambu Hitam" = "cocok untuk dekorasi eksterior dan interior"
  "Bambu Hias" = "digunakan sebagai dekorasi taman, pot tanaman, atau interior ruangan"
  "Bambu Petung" = "digunakan untuk struktur besar seperti jembatan dan bangunan semi-permanen"
  "Bambu Kuning" = "cocok untuk keperluan dekorasi dan kerajinan tangan"

[params.kegunaanList]
  "Bambu Tali" = "digunakan sebagai material bangunan untuk konstruksi ringan"
  "Bambu Steger" = "digunakan sebagai penopang sementara dalam proyek bangunan"
  "Bambu Hitam" = "cocok untuk dekorasi rumah dan taman dengan kesan alami"
  "Bambu Hias" = "digunakan sebagai elemen dekoratif untuk rumah dan taman"
  "Bambu Petung" = "digunakan dalam konstruksi berat dan untuk keperluan industri"
  "Bambu Kuning" = "digunakan untuk bahan kerajinan tangan dan dekorasi"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
   title = "Jual Bambu Tali, Bambu Steger, Bambu Hitam, Bambu Hias | "
   highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"